base/urls.py
from django.urls import path

from .appview import user_views, config_view, file_opt_view, terminal_equ_view
from .appview import log_view
from base.socket_manager import service_regist

app_name = 'base'
urlpatterns = [
    # 用户管理
    path('base/user/to_user_list', user_views.to_user_list, name="user_list"),
    path('base/user/user_query', user_views.user_query),
    # 参数管理
    path('base/config/to_config_list', config_view.to_config_list, name="config_list"),
    path('base/config/config_query', config_view.config_query),
    path('base/config/by_id', config_view.by_id),
    path('base/config/save', config_view.save),
    path('base/config/delete', config_view.delete),
    # 附件操作
    path('sys/file/down_from_remote', file_opt_view.down_from_remote),
    path('sys/file/up_file_to_sch', file_opt_view.up_file_to_sch),
    path('sys/file/downloadById', file_opt_view.downloadById),
    path('sys/file/viewPic', file_opt_view.viewPic),
    path('sys/file/viewThumbPic', file_opt_view.viewThumbPic),
    path('sys/file/viewMp4', file_opt_view.viewMp4),
    path('upload/<path:relative_path_name>', file_opt_view.downByRelativePath),  # 基于upload路径预览(path匹配任何非空字符串, 包含路径分隔符)
    # 日志管理
    path('base/log/to_log_list', log_view.to_log_list, name="log_list"),
    path('base/log/log_query', log_view.log_query),
    path('base/log/by_id', log_view.by_id),
    # 服务注册
    path('base/service/service_regist', service_regist),
    # 终端设备绑定
    path('base/terminal/to_terminal_equ_list', terminal_equ_view.to_terminal_equ_list, name="terminal_equ_list"),
    path('base/terminal/equ_query', terminal_equ_view.equ_query),
    path('base/terminal/save_ytj_equ', terminal_equ_view.save_ytj_equ),  # 保存一个一体机终端设置
    path('base/terminal/by_id', terminal_equ_view.by_id),
    path('base/terminal/save', terminal_equ_view.save),
    path('base/terminal/delete', terminal_equ_view.delete),
    path('base/terminal/batch_set_times', terminal_equ_view.batch_set_times),  # 批量设置开关机时间
    path('base/terminal/my_online_ps', terminal_equ_view.my_online_ps),  # 获取在线的画屏集合
]

sr/urls.py
from django.urls import path
from .appview import hardware_view

app_name = 'sr'
urlpatterns = [
    path('sr/hardware/to_hardware_list', hardware_view.to_hardware_list, name="hd_list"),
    path('sr/hardware/query', hardware_view.hardware_query),
    path('sr/hardware/by_id', hardware_view.by_id),
    path('sr/hardware/save', hardware_view.save),
    path('sr/hardware/delete', hardware_view.delete),
    path('sr/hardware/to_online_hardware', hardware_view.to_online_hardware),
    path('sr/hardware/query_online', hardware_view.query_online),
    path('sr/hardware/bind_hardware', hardware_view.bind_hardware),
    path('sr/hardware/get_box_mac', hardware_view.get_box_mac),
]

zhihuimohe4py/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import include, path
from base.appview import index_views
from base import websocket_terminal
from zhkt import websocket_ytj, websocket_stu


urlpatterns = [
    path(r'favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),  # favicon位置
    path('', index_views.to_index),  # 首页
    path('admin/', admin.site.urls),
    path('', include('base.urls')),  # 基础信息
    path('', include('sr.urls')),  # 盒子和设备相关硬件管理
    path('zhkt/', include('zhkt.urls')),  # 智慧课堂模块
    path('', include('apiweb.urls')),  # 开放的api接口
    # 所有webSocket
    path(r'ecc/ws', websocket_terminal.ws_hp_in),  # 画屏接入智慧魔盒
    path(r'zhktYtj/ws', websocket_ytj.ws_ytj_in),  # 一体机连入智慧魔盒
    path(r'wxs/zhkt4StuWs', websocket_stu.ws_ytj_stu_in),  # 学生端接入智慧魔盒
]

base/models.py
from django.db import models


# base_user表
class User(models.Model):
    user_id = models.BigAutoField(primary_key=True)  # 主键用户Id
    username = models.CharField(max_length=50)  # 用户账号
    userType = models.CharField(max_length=20, null=True)  # 用户类型
    realname = models.CharField(max_length=50, null=True)  # 用户姓名
    dataid = models.CharField(max_length=100, null=True)  # 数据来源Id
    org_label = models.CharField(max_length=200, null=True)  # 部门名称


# base_config表
class Config(models.Model):
    id = models.BigAutoField(primary_key=True)  # 主键Id
    key = models.CharField(max_length=50, null=True)  # key
    value = models.CharField(max_length=1000, null=True)  # value
    remark = models.CharField(max_length=200, null=True)  # 备注


# base_files表
class Files(models.Model):
    id = models.CharField(max_length=50, primary_key=True)  # 主键Id
    file_name = models.CharField(max_length=50, null=True)  # 文件存储名
    file_real_name = models.CharField(max_length=200, null=True)  # 文件真实名
    file_size = models.CharField(max_length=20, null=True)  # 文件大小
    file_path = models.CharField(max_length=100, null=True)  # 文件相对路径
    ext_file_name = models.CharField(max_length=100, null=True)  # 相关扩展文件名
    file_type = models.CharField(max_length=10, null=True)  # 文件类型
    main_id = models.CharField(max_length=50, null=True)  # 关于课堂id


# base_log表
class Log(models.Model):
    id = models.UUIDField(primary_key=True)  # 主键uuid
    module = models.CharField(max_length=64)  # 模块
    content = models.CharField(max_length=1024, null=True)  # 模块内容
    create_time = models.CharField(max_length=64, null=True)  # 创建时间


# base_terminal_equ表(终端设备绑定表)
class Terminal_Equ(models.Model):
    id = models.CharField(max_length=50, primary_key=True)  # 主键Id
    mac = models.CharField(max_length=50, null=True)  # mac地址
    equ_name = models.CharField(max_length=100, null=True)  # 终端设备名称
    alias_name = models.CharField(max_length=50, null=True)  # 别名
    equ_type = models.CharField(max_length=10, null=True)  # 终端类型(一体机/画屏)
    app_version = models.CharField(max_length=20, null=True)  # 所装软件版本
    create_time = models.CharField(max_length=20, null=True)  # 绑定时间
    last_online = models.CharField(max_length=20, null=True)  # 最后上线时间
    close_time = models.CharField(max_length=20, null=True)  # 定时关机时间(设置项)
    weekup_time = models.CharField(max_length=20, null=True)  # 定时开机时间(设置项)
    ps = models.CharField(max_length=500, null=True)  # 备注

templates/base/config_list.html
{%extends "layout/bootstrap-lay.html" %}

{% block mainbody %}
    <!-- 引入验证使用的组件 -->
    {% include 'layout/validate-lay.html' %}

    <body style="padding:10px 10px 5px;overflow-x:hidden;" >

        <div id="rrapp" >
            <!-- 列表区域 -->
            <div v-show=" 'grid' == showType " >
                <div class="row" >
                        <div class="col-md-5 col-sm-5" >
                            <label class="form-lable" style="width:65px;float:left;">参数名：</label>
                            <div style="overflow: hidden;" >
                                <input class="form-control input-sm" type="text" v-model="queryData.keyLike">
                            </div>
                        </div>

                        <div class="col-md-5 col-sm-5" >
                            <label class="form-lable" style="width:65px;float:left;">参数值：</label>
                            <div style="overflow: hidden;" >
                                <input class="form-control input-sm" type="text" v-model="queryData.valueLike">
                            </div>
                        </div>

                        <div class="col-md-2 col-sm-2" >
                            <button class="btn btn-info" type="button" @click="searchGridVm" >
                                <i class="glyphicon glyphicon-search" ></i>&nbsp;搜索
                            </button>
                        </div>
                </div>

                <div style="padding:5px 0 10px;" >
                    <a class="btn btn-primary" @click="addVm" ><i class="fa fa-plus"></i>&nbsp;新建参数设置</a>&nbsp;&nbsp;
                </div>

                <table id="js_jqGrid"></table>
                <div id="js_gridPager"></div>
            </div>

            <!-- 表单区域 -->
            <div v-show=" 'form' == showType " class="panel panel-default" >
                <div class="panel-heading" >参数设置信息</div>

                <form id="js_form" method="post" class="form-horizontal" style="width:100%;padding:15px;" >

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>
                                参数名：<span class="required_star">*</span>
                            </label>
                        </div>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" v-model="entity.key" name="key" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>
                                参数值：<span class="required_star">*</span>
                            </label>
                        </div>
                        <div class="col-sm-9">
                            <textarea class="form-control" style="margin-top:5px;" rows="5"
                            v-model="entity.value" placeholder="请输入参数，不超过500字符" required ></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>备注：</label>
                        </div>
                        <div class="col-sm-9" >
                            <textarea class="form-control" style="margin-top:5px;" rows="5"
                            v-model="entity.remark" placeholder="请输入备注，不超过200字" ></textarea>
                        </div>
                    </div>

                    <div>
                        <div class="col-sm-2 control-label"></div>
                        <input type="button" class="btn btn-success" @click="saveVm" value="保存"/>&nbsp;&nbsp;
                        <input type="button" class="btn btn-warning" @click="reloadVm" value="取消"/>
                    </div>
                </form>
            </div>

            <div v-show=" 'view' == showType " class="panel panel-default" >
                <div class="panel-heading" >参数设置详情</div>

                <div class="form-horizontal" style="width:100%;padding:15px;" >

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>参数名：</label>
                        </div>
                        <div class="col-sm-9">[[entity.key]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>参数值：</label>
                        </div>
                        <div class="col-sm-9">[[entity.value]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>备注：</label>
                        </div>
                        <div class="col-sm-9" >[[entity.remark]]&nbsp;</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div>
                        <div class="col-sm-2 text_right"></div>
                        <input type="button" class="btn btn-warning" @click="reloadVm" value="返回"/>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <script src="/static/js/base/config_list.js" type="text/javascript"></script>
{% endblock %}

templates/base/index.html
{%extends "layout/layui-lay.html" %}

{% block mainbody %}

    <body class="layui-layout-body">

        <!-- 页面布局 -->
        <div class="layui-layout layui-layout-admin">
            <div class="layui-header">
                <div class="layui-logo">智慧魔盒控制台</div>

                <!-- 右上角用户信息区域 -->
                <ul class="layui-nav layui-layout-right">

                    <li class="layui-nav-item">
                        <!-- 点击姓名查看我的信息 -->
                        <a href="javascript:void(0);" >超级管理员</a>
                    </li>
                </ul>
            </div>

            <div class="layui-side layui-bg-black">
                <div class="layui-side-scroll">

                    <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                    <ul class="layui-nav layui-nav-tree" >
                        <li class="layui-nav-item layui-this">
                            <a href="javascript:openMenuUrl('{% url 'base:user_list' %}');" >用户列表</a>
                        </li>
                        <li class="layui-nav-item">
                            <a href="javascript:openMenuUrl('{% url 'base:config_list' %}');" >参数管理</a>
                        </li>

                        <li class="layui-nav-item">
                            <a href="javascript:openMenuUrl('{% url 'base:terminal_equ_list' %}');" >终端设备管理</a>
                        </li>

                        <li class="layui-nav-item">
                            <a href="javascript:openMenuUrl('');" >智慧课堂监控</a>
                        </li>

                        <li class="layui-nav-item">
                            <a href="javascript:openMenuUrl('{% url 'sr:hd_list' %}');" >设备管理</a>
                        </li>

                        <li class="layui-nav-item">
                            <a href="javascript:openMenuUrl('{% url 'base:log_list' %}');" >系统日志</a>
                        </li>

                    </ul>
                </div>
            </div>

            <div class="layui-body" style="bottom:0px;overflow:hidden;" >
                <iframe height="100%" width="100%" frameBorder="0" allowTransparency="true"
                id="js_frame" src="/base/user/to_user_list" ></iframe>
            </div>
        </div>
    </body>

    <script>
    layui.use([ 'element' ], function(){

    });

    //点击事件: 打开菜单地址
    function openMenuUrl(url){
        $('#js_frame').attr('src', url);
    }
    </script>

{% endblock %}

templates/base/log_list.html
{%extends "layout/bootstrap-lay.html" %}

{% block mainbody %}

    <body style="padding:10px 10px 5px;overflow-x:hidden;" >

        <div id="rrapp" >
            <!-- 列表区域 -->
            <div v-show=" 'grid' == showType " >
                <div class="row" >
                        <div class="col-md-5 col-sm-5" >
                            <label class="form-lable" style="width:65px;float:left;">模块：</label>
                            <div style="overflow: hidden;" >
                                <input class="form-control input-sm" type="text" v-model="queryData.module">
                            </div>
                        </div>

                        <div class="col-md-5 col-sm-5" >
                            <label class="form-lable" style="width:65px;float:left;">内容：</label>
                            <div style="overflow: hidden;" >
                                <input class="form-control input-sm" type="text" v-model="queryData.content">
                            </div>
                        </div>

                        <div class="col-md-2 col-sm-2" >
                            <button class="btn btn-info" type="button" @click="searchGridVm" >
                                <i class="glyphicon glyphicon-search" ></i>&nbsp;搜索
                            </button>
                        </div>
                </div>

                <table id="js_jqGrid"></table>
                <div id="js_gridPager"></div>
            </div>

            <div v-show=" 'view' == showType " class="panel panel-default" >
                <div class="panel-heading" >日志详情</div>

                <div class="form-horizontal" style="width:100%;padding:15px;" >

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>模块：</label>
                        </div>
                        <div class="col-sm-9">[[entity.module]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>内容：</label>
                        </div>
                        <div class="col-sm-9">[[entity.content]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>创建时间</label>
                        </div>
                        <div class="col-sm-9" >[[entity.create_time]]&nbsp;</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div>
                        <div class="col-sm-2 text_right"></div>
                        <input type="button" class="btn btn-warning" @click="reloadVm" value="返回"/>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <script src="/static/js/base/log_list.js" type="text/javascript"></script>
{% endblock %}

templates/base/terminal_equ_list.html
{%extends "layout/bootstrap-lay.html" %}

{% block mainbody %}
    <!-- 引入验证使用的组件 -->
    {% include 'layout/validate-lay.html' %}

    <body style="padding:10px 10px 5px;overflow-x:hidden;" >

        <div id="rrapp" >
            <!-- 列表区域 -->
            <div v-show=" 'grid' == showType " >
                <div class="row" >
                    <div class="col-md-3 col-sm-3" >
                        <label class="form-lable" style="width:80px;float:left;">mac地址：</label>
                        <div style="overflow:hidden;" >
                            <input class="form-control input-sm" type="text" v-model="queryData.macLike" >
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-3" >
                        <label class="form-lable" style="width:80px;float:left;">设备名称：</label>
                        <div style="overflow:hidden;" >
                            <input class="form-control input-sm" type="text" v-model="queryData.equNameLike" >
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-3" >
                        <label class="form-lable" style="width:80px;float:left;">终端类型：</label>
                        <div style="overflow:hidden;" >
                            <select class="form-control input-sm" v-model="queryData.equType" >
                                <option value="" >--请选择--</option>
                                <option value="ps" >画屏</option>
                                <option value="ytj" >一体机</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-3" >
                        <button type="button" class="btn btn-info btn-sm" @click="searchGridVm" >
                            <i class="glyphicon glyphicon-search"></i>&nbsp;查询
                        </button>
                    </div>
                </div>

                <div style="padding:8px 0 10px;" >
                    <a class="btn btn-primary" @click="addPsVm" ><i class="fa fa-plus"></i>&nbsp;新增画屏</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" @click="toBatchSetTimeVm" ><i class="glyphicon glyphicon-adjust"></i>&nbsp;批量设置开关机</a>&nbsp;&nbsp;
                </div>

                <table id="js_jqGrid"></table>
                <div id="js_gridPager"></div>
            </div>

            <!-- 表单区域 -->
            <div v-show=" 'form' == showType " class="panel panel-default" >
                <div class="panel-heading" >终端设备维护</div>

                <form id="js_form" method="post" class="form-horizontal" style="width:100%;padding:15px;" >

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>
                                mac地址：<span class="required_star">*</span>
                            </label>
                        </div>
                        <div class="col-sm-9" >
                            <div class="input-group" v-if=" 'ps' == entity.equ_type " >
                                <input type="text" class="form-control" v-model="entity.mac" name="mac" required >
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-default" @click="selOnlinePsVm" >选择在线终端</button>
                                </div>
                            </div>
                            <div v-else >[[entity.mac]]</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>
                                设备名称：<span class="required_star">*</span>
                            </label>
                        </div>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" v-model="entity.equ_name" name="equ_name" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>设备别名：</label>
                        </div>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" v-model="entity.alias_name" name="alias_name" />
                        </div>
                    </div>

                     <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>开机时间：</label>
                        </div>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="weekup_time" name="weekup_time" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>关机时间：</label>
                        </div>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="close_time" name="close_time" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label" >
                            <label>备注：</label>
                        </div>
                        <div class="col-sm-9" >
                            <textarea class="form-control" style="margin-top:5px;"
                            v-model="entity.ps" placeholder="请输入备注，不超过500字" ></textarea>
                        </div>
                    </div>

                    <div>
                        <div class="col-sm-2 control-label"></div>
                        <input type="button" class="btn btn-success" @click="saveVm" value="保存"/>&nbsp;&nbsp;
                        <input type="button" class="btn btn-warning" @click="reloadVm" value="取消"/>
                    </div>
                </form>
            </div>

            <div v-show=" 'view' == showType " class="panel panel-default" >
                <div class="panel-heading" >终端设备详情</div>

                <div class="form-horizontal" style="width:100%;padding:15px;" >

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>mac地址：</label>
                        </div>
                        <div class="col-sm-9">[[entity.mac]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>设备名称：</label>
                        </div>
                        <div class="col-sm-9">[[entity.equ_name]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>设备别名：</label>
                        </div>
                        <div class="col-sm-9">[[entity.alias_name]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>开机时间：</label>
                        </div>
                        <div class="col-sm-9">[[entity.weekup_time]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>关机时间：</label>
                        </div>
                        <div class="col-sm-9">[[entity.close_time]]</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div class="form-group">
                        <div class="col-sm-2 text_right" >
                            <label>备注：</label>
                        </div>
                        <div class="col-sm-9" >[[entity.ps]]&nbsp;</div>
                    </div>
                    <div class="hr-line-dashed" ></div>

                    <div>
                        <div class="col-sm-2 text_right"></div>
                        <input type="button" class="btn btn-warning" @click="reloadVm" value="返回"/>
                    </div>
                </div>
            </div>

            <!--批量设置开关机时间时, 使用的弹窗-->
            <div id="setTimesDiv" style="padding:10px;overflow-x:hidden;display:none;" >
                <div style="margin-top:10px;" >
                    <label class="form-lable" style="width:78px;float:left;" >开机时间：</label>
                    <div style="overflow:hidden;" >
                        <input type="text" class="form-control input-sm" id="set_weekup_time" readonly />
                    </div>
                </div>

                <div style="margin-top:10px;" >
                    <label class="form-lable" style="width:78px;float:left;" >关机时间：</label>
                    <div style="overflow:hidden;" >
                        <input type="text" class="form-control input-sm" id="set_close_time" readonly />
                    </div>
                </div>
            </div>

            <!-- 选择在线终端设备 -->
            <div id="selOnlinePsDiv" style="padding:10px;overflow-x:hidden;display:none;" >

                <div v-for="item in onlinePs" >
                    <div class="radio" >
                        <label>
                            <input type="radio" name="mac" :value="item" v-model="tempMac" >
                            [[item]]
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <script src="/static/js/base/terminal_equ_list.js" type="text/javascript"></script>
{% endblock %}

templates/base/user_list.html
{%extends "layout/bootstrap-lay.html" %}

{% block mainbody %}

    <body style="padding:10px 10px 5px;overflow-x:hidden;" >
        <form id="js_searchBar" >

            <div class="row" style="margin-bottom:8px;" >
                <div class="col-md-3 col-sm-3" >
                    <label class="form-lable" style="width:60px;float:left;">姓名：</label>
                    <div style="overflow:hidden;" >
                        <input class="form-control input-sm" type="text" name="realnameLike" >
                    </div>
                </div>

                <div class="col-md-3 col-sm-3" >
                    <label class="form-lable" style="width:60px;float:left;">账号：</label>
                    <div style="overflow: hidden;" >
                        <input class="form-control input-sm" type="text" name="usernameLike" >
                    </div>
                </div>

                <div class="col-md-3 col-sm-3" >
                    <label class="form-lable" style="width:60px;float:left;">类型：</label>
                    <div style="overflow:hidden;" >
                        <select class="form-control input-sm" name="userType" >
                            <option value="" >--请选择--</option>
                            <option value="8001" >教师</option>
                            <option value="8002" >学生</option>
                        </select>
                    </div>
                </div>

                <div class="col-md-3 col-sm-3" >
                    <button type="button" class="btn btn-info btn-sm" onclick="searchGridFunc()" >
                        <i class="glyphicon glyphicon-search"></i>&nbsp;查询
                    </button>
                </div>
            </div>
        </form>

        <table id="js_jqGrid" ></table>
        <div id="js_gridPager" ></div>
    </body>

    <script src="/static/js/base/user_list.js" type="text/javascript"></script>
{% endblock %}